backend/controllers/ProductController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Product;
use backend\models\ProductSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Product model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Product();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Product model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/CatalogController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\Controller;
use yii\web\NotFoundHttpException;
use common\models\Product;
use common\models\Category;

class CatalogController extends Controller
{
    /**
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionIndex()
    {
        $categoryId = Yii::$app->request->get('id');
        $categories = Category::find()->all();
        $category = null;

        if ($categoryId) {
            $category = Category::findOne($categoryId);
            if (is_null($category)) {
                throw new NotFoundHttpException('Category not found');
            }

            $products = $category->products;
        } else {
            $products = Product::find()->all();
        }

        return $this->render('index', [
            'category' => $category,
            'categories' => $this->getMenuItems($categories, $category ? $category->id : null),
            'products' => $products
        ]);
    }

    /**
     * @param Category[] $categories
     * @param null $activeId
     * @return array
     */
    private function getMenuItems($categories, $activeId = null)
    {
        $menuItems = [];
        foreach ($categories as $category) {
            if ($category->parent_id === null) {
                $menuItems[$category->id] = [
                    'active' => $activeId === $category->id,
                    'label' => $category->title,
                    'url' => ['catalog/index', 'id' => $category->id],
                ];
            } else {
                $this->placeCategory($category, $menuItems, $activeId);
            }
        }
        return $menuItems;
    }

    /**
     * Places category menu item into menu tree
     *
     * @param Category $category
     * @param $menuItems
     * @param int $activeId
     */
    private function placeCategory($category, &$menuItems, $activeId = null)
    {
        foreach ($menuItems as $id => $navLink) {
            if ($category->parent_id === $id) {
                $menuItems[$id]['items'][$category->id] = [
                    'active' => $activeId === $category->id,
                    'label' => $category->title,
                    'url' => ['catalog/index', 'id' => $category->id],
                ];
                break;
            } elseif (!empty($menuItems[$id]['items'])) {
                $this->placeCategory($category, $menuItems[$id]['items']);
            }
        }
    }

    /**
     * Returns IDs of category and all its sub-categories
     *
     * @param Category[] $categories all categories
     * @param int $categoryId id of category to start search with
     * @param array $categoryIds
     * @return array $categoryIds
     */
    private function getCategoryIds($categories, $categoryId, &$categoryIds = [])
    {
        foreach ($categories as $category) {
            if ($category->id == $categoryId || $category->parent_id == $categoryId) {
                $categoryIds[] = $category->id;
            }
            if (isset($categories[$categoryId]['items'])) {
                foreach ($categories[$categoryId]['items'] as $subCategoryId => $subCategory)
                    $this->getCategoryIds($categories, $subCategoryId, $categoryIds);
            }
        }
        return $categoryIds;
    }

}

frontend/views/catalog/index.php
<?php
/**
 * @var yii\web\View $this
 * @var array $categories
 * @var common\models\Product[] $products
 * @var common\models\Category|null $category
 */
use yii\helpers\Url;

//TODO: запилить картинки товаров
?>
<div class="row">
    <div class="col-md-3">
        <div class="nav">
            <h3>Списк категорий</h3>
            <?= $this->render('topics', [
                'categories' => $categories
            ]) ?>
        </div>
    </div>
    <div class="col-md-9">
        <h1><?= ($category ? $category->title : 'Каталог товаров') ?></h1>
        <?php if (!empty($products)): ?>
            <table class="table table-bordered table-hover">
                <?php foreach ($products as $product): ?>
                    <tr>
                        <td>image</td>
                        <td>
                            <div class="title"><a
                                    href="<?= Url::to(['product/view', 'id' => $product->id]) ?>"><?= $product->title ?></a>
                            </div>
                            <div class="text"><?= $product->description ?></div>
                            <div class="price"><?= $product->price ?> рублей</div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php else: ?>
            <div class="error">Здесь товаров нет вообще!</div>
        <?php endif; ?>
    </div>
</div>

frontend/views/catalog/topics.php
<?php

use yii\helpers\Url;

/**
 * @var yii\web\View $this
 * @var array $categories ;
 */
?>
<ul>
    <?php foreach ($categories as $category): ?>
        <li>
            <?php if ($category['active']): ?>
               <b><?= $category['label'] ?></b>
            <?php else: ?>
                <a href="<?= Url::to($category['url']) ?>"><?= $category['label'] ?></a>
            <?php endif; ?>
            <?php if (!empty($category['items'])): ?>
                <?= $this->render('topics', [
                    'categories' => $category['items']
                ]) ?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>